CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR        NOT NULL,
    login    VARCHAR        NOT NULL,
    birthday DATE,
    email    VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id   INTEGER REFERENCES users (id),
    friend_id INTEGER REFERENCES users (id),
    UNIQUE (user_id, friend_id)
);
CREATE TABLE IF NOT EXISTS mpa_rating
(
    id_mpa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating VARCHAR
);

CREATE TABLE IF NOT EXISTS genre
(
    id_genre INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre    VARCHAR
);


CREATE TABLE IF NOT EXISTS films
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR,
    description VARCHAR,
    releaseDate DATE,
    duration    INTEGER,
    rate        INTEGER,
    mpa         INTEGER REFERENCES mpa_rating (id_mpa)
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id INTEGER REFERENCES users (id),
    film_id INTEGER REFERENCES films (id)
);

CREATE TABLE IF NOT EXISTS genre
(
    id_genre INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre    VARCHAR
);

CREATE TABLE IF NOT EXISTS film_genre
(
    id_film  INTEGER REFERENCES films (id),
    id_genre INTEGER REFERENCES genre (id_genre)
)
